#!/usr/bin/env python3
"""versionmap.py IR_EXE V10_EXE V11_EXE > source/version_maps.inc: where the static data segment of the initial release
and of 1.0 lies against 1.1's (the layout SDLPoP2 addresses DS in).

Each build's initialised DS (DS:0 = the "MS Run-Time Library" string - 8) is aligned byte by byte against 1.1's
(difflib); the identical runs give anchors {1.1 offset, delta}: an offset maps with the delta of the last anchor at or
below it (positions carry on through the bytes that differ, which keeps equally long tables and pointer words in
step). The inverse anchors {build offset, delta} map pointers back. Offsets only: no game data."""
import difflib, sys

def ds_of(path):
    d = open(path, 'rb').read()
    i = d.find(b'MS Run-Time Library')
    if i < 8: raise SystemExit('%s: no C runtime data segment' % path)
    return d, i - 8

def anchors(pairs):
    out = []
    for a, b in pairs:
        dl = b - a
        if not out or out[-1][1] != dl: out.append((a, dl))
    return out

ir, v10, v11 = sys.argv[1:4]
d11, o11 = ds_of(v11); a = d11[o11:o11 + 0x27C0]
print('/* generated by tools/versionmap.py: anchors {offset, delta} of the static data segment (DS:0..27C0), see version.c */')
for name, path, n in (('ir', ir, 0x2930), ('v10', v10, 0x27C0)):
    d, o = ds_of(path); b = d[o:o + n]
    sm = difflib.SequenceMatcher(None, a, b, autojunk=False)
    blocks = [bl for bl in sm.get_matching_blocks() if bl.size >= 2]
    fwd = anchors((bl.a, bl.b) for bl in blocks)
    inv = anchors((bl.b, bl.a) for bl in blocks)
    for tag, lst in (('to', fwd), ('from', inv)):
        print('static const int16_t ds_%s_%s[][2] = {' % (tag, name))
        for k in range(0, len(lst), 8): print('\t' + ' '.join('{0x%04X, %d},' % x for x in lst[k:k + 8]))
        print('\t{-1, 0}};')
